language: node_js
node_js:
  - 6
cache:
  directories:
  - docs/vendor/bundle
  - $HOME/.yarn-cache
before_install:
- |
    sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update -qq
    sudo apt-get install -y -qq yarn
    yarn --version
install:
- |
    yarn install
script:
- |
    yarn run lint
    yarn run test:coverage

    # Uploading to coveralls, even though we are not displaying it, because it will look bad in the readme.
    cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
